name: Basic CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show project files
        run: ls -la

      - name: Show notes.txt
        run: cat notes.txt