name: Multiple Jobs Demo

on:
  push:
    branches:
      - main

jobs:

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check files
        run: exit 1

  hello:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from Job 2"