name: Variables Demo

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest

    env:
      MESSAGE: "Hello from GitHub Actions"
      PROJECT: "git-rebase-practice"

    steps:
      - name: Show message
        run: echo "$MESSAGE"

      - name: Show project
        run: echo "$PROJECT"