name: GitHub Context Practice

on:
  push:

jobs:

  info:
    runs-on: ubuntu-latest

    steps:

      - name: Show repository
        run: echo "Repository = ${{ github.repository }}"

      - name: Show branch
        run: echo "Branch = ${{ github.ref_name }}"

      - name: Show commit
        run: echo "Commit = ${{ github.sha }}"

      - name: Show event
        run: echo "Event = ${{ github.event_name }}"

      - name: Show actor
        run: echo "Triggered by = ${{ github.actor }}"