name: Conditions Practice

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Build completed successfully"


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run Tests
        run: |
          echo "Running tests..."
          echo "Tests completed successfully"


  deploy:
    needs: test
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploying to production"


  failure-notification:
    needs: test
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Failure Notification
        run: echo "Something failed!"


  cleanup:
    needs: [build, test, deploy, failure-notification]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup
        run: echo "Cleanup always runs"