name: Job Output Practice

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version-step.outputs.app_version }}

    steps:

      - name: Create version
        id: version-step
        run: echo "app_version=2.5.0" >> "$GITHUB_OUTPUT"


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Show version
        run: echo "Deploying version ${{ needs.build.outputs.version }}"